server:
  port: 8181
rocketmq:
  name-server: localhost:9876 # 访问地址
  producer:
    group: TestTopic # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2

